### ISSUE TITLE
error log

### ISSUE THREAD

**Issue by idksalem** [realoksi/foobar2000-catbox#4]
Discord Rich Presence Integration v1.3.0-beta-6+4aec8f6: artwork uploader exited with status: 4294967295 and error: [56] Failure when receiving data from the peer

**Comment by realoksi** [comment]
Running the current release (v1.0.0-alpha) and feeding it a path manually gives me the same error. After a bit of research [this](https://github.com/Savolae/catbox/issues/34) appears to be the problem. After adding a user-agent, recompiling and running, it works successfully. 
Will clean this up and push to a non-production branch soon, need to further verify this *is* the fix
